apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.applicationName }}-backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
